export const GUEST_MAX_CHARACTERS = 5;
export const USER_MAX_CHARACTERS = 20;
export const KEEPER_MAX_CHARACTERS = 40;
export const ADMIN_MAX_CHARACTERS = 40;

export const USER_MAX_CAMPAIGNS = 5;
export const KEEPER_MAX_CAMPAIGNS = 20;
export const ADMIN_MAX_CAMPAIGNS = 20;

export const USER_MAX_PARTY_GROUPS = 5;
export const KEEPER_MAX_PARTY_GROUPS = 20;
export const ADMIN_MAX_PARTY_GROUPS = 20;

export const USER_MAX_ENCOUNTER_TEMPLATES = 10;
export const KEEPER_MAX_ENCOUNTER_TEMPLATES = 40;
export const ADMIN_MAX_ENCOUNTER_TEMPLATES = 40;

export const CAMPAIGN_MAX_SESSION_NOTES = 100;
export const CAMPAIGN_MAX_PREPARED_ENCOUNTERS = 5;
export const ENCOUNTER_MAX_CREATURES = 20;
export const PARTY_GROUP_MAX_MEMBERS = 10;
export const CHARACTER_COMPANION_LIMIT = 10;

export const ENCOUNTER_INHERITED_CREATURE_ENTRY_MAX_BYTES = 40 * 1024;
export const ENCOUNTER_CREATURE_RECORD_MAX_BYTES = 60 * 1024;
export const ENCOUNTER_CREATURE_LIST_MAX_BYTES = 1024 * 1024;
