export const CONTAINER_OBJECT_LIMIT = 100;
export const INVENTORY_OBJECT_LIMIT = 200;
export const INVENTORY_STACK_QUANTITY_LIMIT = 100;
export const INVENTORY_REFILLABLE_LIMIT = 100;
export const ITEM_MOD_EFFECT_LIMIT = 5;
