export enum ENTRY_CATEGORIES {
  SPELLS = "SPELLS",
  WEAPONS = "WEAPONS",
  ARMOR = "ARMOR",
  ITEMS = "ITEMS",
  BACKGROUNDS = "BACKGROUNDS",
  SPECIES = "SPECIES",
  CLASSES = "CLASSES",
  RULES = "RULES",
  MONSTERS = "MONSTERS"
}

export enum ABILITY_TYPES {
  STR = "STR",
  DEX = "DEX",
  CON = "CON",
  INT = "INT",
  WIS = "WIS",
  CHA = "CHA"
}

export enum DICE_TYPES {
  DICE_TYPE_D4 = "D4",
  DICE_TYPE_D6 = "D6",
  DICE_TYPE_D8 = "D8",
  DICE_TYPE_D10 = "D10",
  DICE_TYPE_D12 = "D12",
  DICE_TYPE_D20 = "D20"
}

export enum RARITY_TYPES {
  COMMON = "COMMON",
  RARE = "RARE",
  EPIC = "EPIC",
  LEGENDARY = "LEGENDARY"
}

export enum DAMAGE_TYPES {
  SLASHING = "SLASHING",
  PIERCING = "PIERCING",
  BLUDGEONING = "BLUDGEONING",
  FIRE = "FIRE",
  COLD = "COLD",
  LIGHTNING = "LIGHTNING",
  THUNDER = "THUNDER",
  FORCE = "FORCE",
  RADIANT = "RADIANT",
  NECROTIC = "NECROTIC",
  POISON = "POISON",
  ACID = "ACID",
  PSYCHIC = "PSYCHIC"
}

export enum COLOR_TYPES {
  WHITE = "#ffffff",
  BLUE = "#0070DD",
  PURPLE = "#A335EE",
  ORANGE = "#FFAA00",
  LIGHTER_GREY = "#5a5f6b",
  DARK_BROWN_TINT = "#2b1e18"
}

export enum ARMOR_TYPES {
  LIGHT_ARMOR = "LIGHT_ARMOR",
  MEDIUM_ARMOR = "MEDIUM_ARMOR",
  HEAVY_ARMOR = "HEAVY_ARMOR",
  SHIELD = "SHIELD"
}

export enum WEAPON_TYPES {
  SIMPLE_MELEE = "SIMPLE_MELEE",
  MARTIAL_MELEE = "MARTIAL_MELEE",
  SIMPLE_RANGED = "SIMPLE_RANGED",
  MARTIAL_RANGED = "MARTIAL_RANGED",
  FINESSE = "FINESSE",
  VERSATILE = "VERSATILE",
  TWO_HANDED = "TWO_HANDED"
}

export enum SPELL_TYPES {
  CANTRIP = "CANTRIP",
  FULL_ACTION = "FULL_ACTION",
  BONUS_ACTION = "BONUS_ACTION"
}

export enum ITEM_TYPES {
  ADVENTURING_GEAR = "ADVENTURING_GEAR",
  TOOLKIT = "TOOLKIT"
}

export enum BACKGROUND_TYPES {
  RELIGIOUS = "RELIGIOUS",
  UNDERWORLD = "UNDERWORLD",
  PERFORMER = "PERFORMER",
  COMMONER = "COMMONER",
  CRAFT = "CRAFT",
  RECLUSIVE = "RECLUSIVE",
  NOBILITY = "NOBILITY",
  WILDERNESS = "WILDERNESS",
  SCHOLAR = "SCHOLAR",
  SEAFARING = "SEAFARING",
  MILITARY = "MILITARY",
  URBAN_SURVIVAL = "URBAN_SURVIVAL"
}

export enum SPECIES_TYPES {
  HUMANOID = "HUMANOID",
  FEY_ANCESTRY = "FEY_ANCESTRY",
  HARDY = "HARDY",
  ARCANE_AFFINITY = "ARCANE_AFFINITY",
  DRACONIC_LINEAGE = "DRACONIC_LINEAGE"
}

export enum CLASS_TYPES {
  MARTIAL = "MARTIAL",
  ARCANE = "ARCANE",
  DIVINE = "DIVINE",
  PRIMAL = "PRIMAL",
  SUPPORT = "SUPPORT",
  SKILL_EXPERT = "SKILL_EXPERT"
}

export enum GENERAL_PROFICIENCIES {
  SIMPLE_WEAPONS = "SIMPLE_WEAPONS",
  MARTIAL_WEAPONS = "MARTIAL_WEAPONS",
  LIGHT_ARMOR = "LIGHT_ARMOR",
  MEDIUM_ARMOR = "MEDIUM_ARMOR",
  HEAVY_ARMOR = "HEAVY_ARMOR",
  SHIELDS = "SHIELDS"
}

export enum TOOL_PROFICIENCIES {
  THIEVES_TOOLKIT = "THIEVES_TOOLKIT",
  SMITHS_TOOLKIT = "SMITHS_TOOLKIT",
  DISGUIDE_KIT = "DISGUIDE_KIT",
  DISARM_KIT = "DISARM_KIT"
}

export enum RULE_TYPES {
  CORE = "CORE",
  COMBAT = "COMBAT",
  EXPLORATION = "EXPLORATION",
  SOCIAL = "SOCIAL",
  CONDITIONS = "CONDITIONS"
}

export enum MONSTER_TYPES {
  BEAST = "BEAST",
  UNDEAD = "UNDEAD",
  DRAGON = "DRAGON",
  HUMANOID = "HUMANOID",
  FIEND = "FIEND",
  BOSS = "BOSS"
}
