export enum ENTRY_CATEGORIES {
  SPELLS = "SPELLS",
  WEAPONS = "WEAPONS",
  ARMOR = "ARMOR",
  ITEMS = "ITEMS",
  BACKGROUNDS = "BACKGROUNDS",
  SPECIES = "SPECIES",
  CLASSES = "CLASSES",
  RULES = "RULES",
  MONSTERS = "MONSTERS"
}

export enum FEAT_CATEGORY {
  ORIGIN = "ORIGIN",
  GENERAL = "GENERAL",
  FIGHTING_STYLE = "FIGHTING_STYLE",
  EPIC_BOON = "EPIC_BOON"
}

export enum FEATS {
  ABILITY_SCORE_IMPROVEMENT = "ABILITY_SCORE_IMPROVEMENT",
  ALERT = "ALERT",
  ARCHERY = "ARCHERY",
  BLESSED_WARRIOR = "BLESSED_WARRIOR",
  DRUIDIC_WARRIOR = "DRUIDIC_WARRIOR",
  BOON_OF_COMBAT_PROWESS = "BOON_OF_COMBAT_PROWESS",
  BOON_OF_DIMENSIONAL_TRAVEL = "BOON_OF_DIMENSIONAL_TRAVEL",
  BOON_OF_FATE = "BOON_OF_FATE",
  BOON_OF_IRRESISTIBLE_OFFENSE = "BOON_OF_IRRESISTIBLE_OFFENSE",
  BOON_OF_THE_NIGHT_SPIRIT = "BOON_OF_THE_NIGHT_SPIRIT",
  BOON_OF_SPELL_RECALL = "BOON_OF_SPELL_RECALL",
  BOON_OF_TRUESIGHT = "BOON_OF_TRUESIGHT",
  DEFENSE = "DEFENSE",
  GRAPPLER = "GRAPPLER",
  GREAT_WEAPON_FIGHTING = "GREAT_WEAPON_FIGHTING",
  MAGIC_INITIATE = "MAGIC_INITIATE",
  SAVAGE_ATTACKER = "SAVAGE_ATTACKER",
  SKILLED = "SKILLED",
  TWO_WEAPON_FIGHTING = "TWO_WEAPON_FIGHTING"
}

export enum REACTION {
  COUNTERCHARM = "COUNTERCHARM",
  DEFLECT_ATTACKS = "DEFLECT_ATTACKS",
  SLOW_FALL = "SLOW_FALL",
  UNCANNY_DODGE = "UNCANNY_DODGE"
}

export enum ABILITY_TYPES {
  STR = "STR",
  DEX = "DEX",
  CON = "CON",
  INT = "INT",
  WIS = "WIS",
  CHA = "CHA"
}

export enum DICE_TYPES {
  DICE_TYPE_D4 = "D4",
  DICE_TYPE_D6 = "D6",
  DICE_TYPE_D8 = "D8",
  DICE_TYPE_D10 = "D10",
  DICE_TYPE_D12 = "D12",
  DICE_TYPE_D20 = "D20"
}

export enum DICE {
  D4 = "D4",
  D6 = "D6",
  D8 = "D8",
  D10 = "D10",
  D12 = "D12",
  D20 = "D20"
}

export enum DURATION {
  CONCENTRATION = "CONCENTRATION"
}

export enum RARITY_TYPES {
  CUSTOM = "CUSTOM",
  COMMON = "COMMON",
  RARE = "RARE",
  EPIC = "EPIC",
  LEGENDARY = "LEGENDARY"
}

export enum DAMAGE_TYPES {
  SLASHING = "SLASHING",
  PIERCING = "PIERCING",
  BLUDGEONING = "BLUDGEONING",
  FIRE = "FIRE",
  COLD = "COLD",
  LIGHTNING = "LIGHTNING",
  THUNDER = "THUNDER",
  FORCE = "FORCE",
  RADIANT = "RADIANT",
  NECROTIC = "NECROTIC",
  POISON = "POISON",
  ACID = "ACID",
  PSYCHIC = "PSYCHIC"
}

export enum DAMAGE_TYPE {
  PIERCING = "PIERCING",
  BLUDGEONING = "BLUDGEONING",
  SLASHING = "SLASHING",
  COLD = "COLD",
  FIRE = "FIRE",
  LIGHTNING = "LIGHTNING",
  THUNDER = "THUNDER",
  POISON = "POISON",
  ACID = "ACID",
  NECROTIC = "NECROTIC",
  RADIANT = "RADIANT",
  FORCE = "FORCE",
  PSYCHIC = "PSYCHIC"
}

export enum COLOR_TYPES {
  WHITE = "#ffffff",
  BLUE = "#0070DD",
  PURPLE = "#A335EE",
  ORANGE = "#FFAA00",
  LIGHTER_GREY = "#5a5f6b",
  DARK_BROWN_TINT = "#2b1e18"
}

export enum ARMOR_TYPES {
  LIGHT_ARMOR = "LIGHT_ARMOR",
  MEDIUM_ARMOR = "MEDIUM_ARMOR",
  HEAVY_ARMOR = "HEAVY_ARMOR",
  SHIELD = "SHIELD"
}

export enum WEAPON_TYPES {
  SIMPLE_MELEE = "SIMPLE_MELEE",
  MARTIAL_MELEE = "MARTIAL_MELEE",
  SIMPLE_RANGED = "SIMPLE_RANGED",
  MARTIAL_RANGED = "MARTIAL_RANGED",
  FINESSE = "FINESSE",
  VERSATILE = "VERSATILE",
  TWO_HANDED = "TWO_HANDED"
}

export enum WEAPON_TRAINING {
  SIMPLE = "SIMPLE",
  MARTIAL = "MARTIAL"
}

export enum WEAPON_BASE {
  CLUB = "CLUB",
  DAGGER = "DAGGER",
  GREATCLUB = "GREATCLUB",
  HANDAXE = "HANDAXE",
  JAVELIN = "JAVELIN",
  LIGHT_HAMMER = "LIGHT_HAMMER",
  MACE = "MACE",
  QUARTERSTAFF = "QUARTERSTAFF",
  SICKLE = "SICKLE",
  SPEAR = "SPEAR",
  DART = "DART",
  LIGHT_CROSSBOW = "LIGHT_CROSSBOW",
  SHORTBOW = "SHORTBOW",
  SLING = "SLING",
  BATTLEAXE = "BATTLEAXE",
  FLAIL = "FLAIL",
  GLAIVE = "GLAIVE",
  GREATAXE = "GREATAXE",
  GREATSWORD = "GREATSWORD",
  HALBERD = "HALBERD",
  LANCE = "LANCE",
  LONGSWORD = "LONGSWORD",
  MAUL = "MAUL",
  MORNINGSTAR = "MORNINGSTAR",
  PIKE = "PIKE",
  RAPIER = "RAPIER",
  SCIMITAR = "SCIMITAR",
  SHORTSWORD = "SHORTSWORD",
  TRIDENT = "TRIDENT",
  WARHAMMER = "WARHAMMER",
  WAR_PICK = "WAR_PICK",
  WHIP = "WHIP",
  BLOWGUN = "BLOWGUN",
  HAND_CROSSBOW = "HAND_CROSSBOW",
  HEAVY_CROSSBOW = "HEAVY_CROSSBOW",
  LONGBOW = "LONGBOW",
  MUSKET = "MUSKET",
  PISTOL = "PISTOL"
}

export enum WEAPON_COMBAT_TYPE {
  MELEE = "MELEE",
  RANGED = "RANGED"
}

export enum WEAPON_PROPERTY {
  AMMUNITION = "AMMUNITION",
  FINESSE = "FINESSE",
  HEAVY = "HEAVY",
  LIGHT = "LIGHT",
  LOADING = "LOADING",
  RANGE = "RANGE",
  REACH = "REACH",
  THROWN = "THROWN",
  TWO_HANDED = "TWO_HANDED",
  VERSATILE = "VERSATILE"
}

export enum WEAPON_MASTERY {
  CLEAVE = "CLEAVE",
  GRAZE = "GRAZE",
  NICK = "NICK",
  PUSH = "PUSH",
  SAP = "SAP",
  SLOW = "SLOW",
  TOPPLE = "TOPPLE",
  VEX = "VEX"
}

export enum CURRENCY_TYPE {
  CP = "CP",
  SP = "SP",
  EP = "EP",
  GP = "GP",
  PP = "PP"
}

export enum SPELL_TYPES {
  CANTRIP = "CANTRIP",
  FULL_ACTION = "FULL_ACTION",
  BONUS_ACTION = "BONUS_ACTION"
}

export enum ACTION_TYPE {
  ACTION = "ACTION",
  BONUS_ACTION = "BONUS_ACTION",
  REACTION = "REACTION",
  MINUTE = "MINUTE",
  TEN_MINUTES = "TEN_MINUTES",
  HOUR = "HOUR",
  EIGHT_HOURS = "EIGHT_HOURS",
  TWELVE_HOURS = "TWELVE_HOURS",
  TWENTY_FOUR_HOURS = "TWENTY_FOUR_HOURS"
}

export enum MAGIC_SCHOOL {
  ABJURATION = "ABJURATION",
  CONJURATION = "CONJURATION",
  DIVINATION = "DIVINATION",
  ENCHANTMENT = "ENCHANTMENT",
  EVOCATION = "EVOCATION",
  ILLUSION = "ILLUSION",
  NECROMANCY = "NECROMANCY",
  TRANSMUTATION = "TRANSMUTATION"
}

export enum SPELL_COMPONENT {
  V = "V",
  S = "S",
  M = "M"
}

export enum SPELL_LIST_CLASS {
  ARTIFICER = "ARTIFICER",
  BARD = "BARD",
  CLERIC = "CLERIC",
  DRUID = "DRUID",
  PALADIN = "PALADIN",
  RANGER = "RANGER",
  SORCERER = "SORCERER",
  WARLOCK = "WARLOCK",
  WIZARD = "WIZARD"
}

export enum ITEM_TYPES {
  ADVENTURING_GEAR = "ADVENTURING_GEAR",
  TOOLKIT = "TOOLKIT"
}

export enum BACKGROUND_TYPES {
  RELIGIOUS = "RELIGIOUS",
  UNDERWORLD = "UNDERWORLD",
  PERFORMER = "PERFORMER",
  COMMONER = "COMMONER",
  CRAFT = "CRAFT",
  RECLUSIVE = "RECLUSIVE",
  NOBILITY = "NOBILITY",
  WILDERNESS = "WILDERNESS",
  SCHOLAR = "SCHOLAR",
  SEAFARING = "SEAFARING",
  MILITARY = "MILITARY",
  URBAN_SURVIVAL = "URBAN_SURVIVAL"
}

export enum SPECIES_TYPES {
  HUMANOID = "HUMANOID",
  FEY_ANCESTRY = "FEY_ANCESTRY",
  HARDY = "HARDY",
  ARCANE_AFFINITY = "ARCANE_AFFINITY",
  DRACONIC_LINEAGE = "DRACONIC_LINEAGE"
}

export enum CLASS_TYPES {
  MARTIAL = "MARTIAL",
  ARCANE = "ARCANE",
  DIVINE = "DIVINE",
  PRIMAL = "PRIMAL",
  SUPPORT = "SUPPORT",
  SKILL_EXPERT = "SKILL_EXPERT"
}

export enum CLASS_FEATURE {
  RAGE = "RAGE",
  UNARMORED_DEFENSE = "UNARMORED_DEFENSE",
  WEAPON_MASTERY = "WEAPON_MASTERY",
  LAY_ON_HANDS = "LAY_ON_HANDS",
  PALADINS_SMITE = "PALADIN'S_SMITE",
  PALADIN_SUBCLASS = "PALADIN_SUBCLASS",
  FIGHTING_STYLE = "FIGHTING_STYLE",
  SECOND_WIND = "SECOND_WIND",
  ACTION_SURGE = "ACTION_SURGE",
  TACTICAL_MIND = "TACTICAL_MIND",
  FIGHTER_SUBCLASS = "FIGHTER_SUBCLASS",
  MARTIAL_ARTS = "MARTIAL_ARTS",
  MONKS_FOCUS = "MONK'S_FOCUS",
  UNARMORED_MOVEMENT = "UNARMORED_MOVEMENT",
  UNCANNY_METABOLISM = "UNCANNY_METABOLISM",
  DEFLECT_ATTACKS = "DEFLECT_ATTACKS",
  MONK_SUBCLASS = "MONK_SUBCLASS",
  BARDIC_INSPIRATION = "BARDIC_INSPIRATION",
  SPELLCASTING = "SPELLCASTING",
  DIVINE_ORDER = "DIVINE_ORDER",
  CHANNEL_DIVINITY = "CHANNEL_DIVINITY",
  CLERIC_SUBCLASS = "CLERIC_SUBCLASS",
  DRUIDIC = "DRUIDIC",
  PRIMAL_ORDER = "PRIMAL_ORDER",
  WILD_SHAPE = "WILD_SHAPE",
  WILD_COMPANION = "WILD_COMPANION",
  DRUID_SUBCLASS = "DRUID_SUBCLASS",
  EXPERTISE = "EXPERTISE",
  JACK_OF_ALL_TRADES = "JACK_OF_ALL_TRADES",
  BARD_SUBCLASS = "BARD_SUBCLASS",
  FONT_OF_INSPIRATION = "FONT_OF_INSPIRATION",
  COUNTERCHARM = "COUNTERCHARM",
  MAGICAL_SECRETS = "MAGICAL_SECRETS",
  SUPERIOR_INSPIRATION = "SUPERIOR_INSPIRATION",
  WORDS_OF_CREATION = "WORDS_OF_CREATION",
  SEAR_UNDEAD = "SEAR_UNDEAD",
  BLESSED_STRIKES = "BLESSED_STRIKES",
  DIVINE_INTERVENTION = "DIVINE_INTERVENTION",
  IMPROVED_BLESSED_STRIKES = "IMPROVED_BLESSED_STRIKES",
  GREATER_DIVINE_INTERVENTION = "GREATER_DIVINE_INTERVENTION",
  WILD_RESURGENCE = "WILD_RESURGENCE",
  ELEMENTAL_FURY = "ELEMENTAL_FURY",
  IMPROVED_ELEMENTAL_FURY = "IMPROVED_ELEMENTAL_FURY",
  BEAST_SPELLS = "BEAST_SPELLS",
  ARCHDRUID = "ARCHDRUID",
  TACTICAL_SHIFT = "TACTICAL_SHIFT",
  INDOMITABLE = "INDOMITABLE",
  TACTICAL_MASTER = "TACTICAL_MASTER",
  TWO_EXTRA_ATTACKS = "TWO_EXTRA_ATTACKS",
  STUDIED_ATTACKS = "STUDIED_ATTACKS",
  THREE_EXTRA_ATTACKS = "THREE_EXTRA_ATTACKS",
  SLOW_FALL = "SLOW_FALL",
  STUNNING_STRIKE = "STUNNING_STRIKE",
  EMPOWERED_STRIKES = "EMPOWERED_STRIKES",
  EVASION = "EVASION",
  ACROBATIC_MOVEMENT = "ACROBATIC_MOVEMENT",
  HEIGHTENED_FOCUS = "HEIGHTENED_FOCUS",
  SELF_RESTORATION = "SELF_RESTORATION",
  DEFLECT_ENERGY = "DEFLECT_ENERGY",
  DISCIPLINED_SURVIVOR = "DISCIPLINED_SURVIVOR",
  PERFECT_FOCUS = "PERFECT_FOCUS",
  SUPERIOR_DEFENSE = "SUPERIOR_DEFENSE",
  BODY_AND_MIND = "BODY_AND_MIND",
  FAITHFUL_STEED = "FAITHFUL_STEED",
  AURA_OF_PROTECTION = "AURA_OF_PROTECTION",
  ABJURE_FOES = "ABJURE_FOES",
  AURA_OF_COURAGE = "AURA_OF_COURAGE",
  RADIANT_STRIKES = "RADIANT_STRIKES",
  RESTORING_TOUCH = "RESTORING_TOUCH",
  AURA_EXPANSION = "AURA_EXPANSION",
  FAVORED_ENEMY = "FAVORED_ENEMY",
  DEFT_EXPLORER = "DEFT_EXPLORER",
  RANGER_SUBCLASS = "RANGER_SUBCLASS",
  ROVING = "ROVING",
  TIRELESS = "TIRELESS",
  RELENTLESS_HUNTER = "RELENTLESS_HUNTER",
  NATURES_VEIL = "NATURE'S_VEIL",
  PRECISE_HUNTER = "PRECISE_HUNTER",
  FERAL_SENSES = "FERAL_SENSES",
  FOE_SLAYER = "FOE_SLAYER",
  SNEAK_ATTACK = "SNEAK_ATTACK",
  THIEVES_CANT = "THIEVES_CANT",
  CUNNING_ACTION = "CUNNING_ACTION",
  ROGUE_SUBCLASS = "ROGUE_SUBCLASS",
  STEADY_AIM = "STEADY_AIM",
  CUNNING_STRIKE = "CUNNING_STRIKE",
  UNCANNY_DODGE = "UNCANNY_DODGE",
  RELIABLE_TALENT = "RELIABLE_TALENT",
  IMPROVED_CUNNING_STRIKE = "IMPROVED_CUNNING_STRIKE",
  DEVIOUS_STRIKES = "DEVIOUS_STRIKES",
  SLIPPERY_MIND = "SLIPPERY_MIND",
  ELUSIVE = "ELUSIVE",
  STROKE_OF_LUCK = "STROKE_OF_LUCK",
  INNATE_SORCERY = "INNATE_SORCERY",
  FONT_OF_MAGIC = "FONT_OF_MAGIC",
  METAMAGIC = "METAMAGIC",
  SORCERER_SUBCLASS = "SORCERER_SUBCLASS",
  SORCEROUS_RESTORATION = "SORCEROUS_RESTORATION",
  SORCERY_INCARNATE = "SORCERY_INCARNATE",
  ARCANE_APOTHEOSIS = "ARCANE_APOTHEOSIS",
  ELDRITCH_INVOCATIONS = "ELDRITCH_INVOCATIONS",
  PACT_MAGIC = "PACT_MAGIC",
  MAGICAL_CUNNING = "MAGICAL_CUNNING",
  WARLOCK_SUBCLASS = "WARLOCK_SUBCLASS",
  CONTACT_PATRON = "CONTACT_PATRON",
  MYSTIC_ARCANUM = "MYSTIC_ARCANUM",
  ELDRITCH_MASTER = "ELDRITCH_MASTER",
  RITUAL_ADEPT = "RITUAL_ADEPT",
  ARCANE_RECOVERY = "ARCANE_RECOVERY",
  SCHOLAR = "SCHOLAR",
  WIZARD_SUBCLASS = "WIZARD_SUBCLASS",
  MEMORIZE_SPELL = "MEMORIZE_SPELL",
  SPELL_MASTERY = "SPELL_MASTERY",
  SIGNATURE_SPELLS = "SIGNATURE_SPELLS",
  DANGER_SENSE = "DANGER_SENSE",
  RECKLESS_ATTACK = "RECKLESS_ATTACK",
  BARBARIAN_SUBCLASS = "BARBARIAN_SUBCLASS",
  PRIMAL_KNOWLEDGE = "PRIMAL_KNOWLEDGE",
  ABILITY_SCORE_IMPROVEMENT = "ABILITY_SCORE_IMPROVEMENT",
  EXTRA_ATTACK = "EXTRA_ATTACK",
  FAST_MOVEMENT = "FAST_MOVEMENT",
  SUBCLASS_FEATURE = "SUBCLASS_FEATURE",
  FERAL_INSTINCT = "FERAL_INSTINCT",
  INSTINCTIVE_POUNCE = "INSTINCTIVE_POUNCE",
  BRUTAL_STRIKE = "BRUTAL_STRIKE",
  RELENTLESS_RAGE = "RELENTLESS_RAGE",
  IMPROVED_BRUTAL_STRIKE = "IMPROVED_BRUTAL_STRIKE",
  PERSISTENT_RAGE = "PERSISTENT_RAGE",
  INDOMITABLE_MIGHT = "INDOMITABLE_MIGHT",
  EPIC_BOON = "EPIC_BOON",
  PRIMAL_CHAMPION = "PRIMAL_CHAMPION"
}

export enum GENERAL_PROFICIENCIES {
  SIMPLE_WEAPONS = "SIMPLE_WEAPONS",
  MARTIAL_WEAPONS = "MARTIAL_WEAPONS",
  LIGHT_ARMOR = "LIGHT_ARMOR",
  MEDIUM_ARMOR = "MEDIUM_ARMOR",
  HEAVY_ARMOR = "HEAVY_ARMOR",
  SHIELDS = "SHIELDS"
}

export enum TOOL_PROFICIENCIES {
  THIEVES_TOOLKIT = "THIEVES_TOOLKIT",
  SMITHS_TOOLKIT = "SMITHS_TOOLKIT",
  DISGUIDE_KIT = "DISGUIDE_KIT",
  DISARM_KIT = "DISARM_KIT"
}

export enum RULE_TYPES {
  CORE = "CORE",
  COMBAT = "COMBAT",
  EXPLORATION = "EXPLORATION",
  SOCIAL = "SOCIAL",
  CONDITIONS = "CONDITIONS"
}

export enum MONSTER_TYPES {
  BEAST = "BEAST",
  UNDEAD = "UNDEAD",
  DRAGON = "DRAGON",
  HUMANOID = "HUMANOID",
  FIEND = "FIEND",
  BOSS = "BOSS"
}
