export enum ENTRY_CATEGORIES {
  SPELLS = "SPELLS",
  WEAPONS = "WEAPONS",
  ARMOR = "ARMOR",
  ITEMS = "ITEMS",
  BACKGROUNDS = "BACKGROUNDS",
  SPECIES = "SPECIES",
  CLASSES = "CLASSES",
  RULES = "RULES",
  MONSTERS = "MONSTERS"
}

export enum ABILITY_TYPES {
  STR = "STR",
  DEX = "DEX",
  CON = "CON",
  INT = "INT",
  WIS = "WIS",
  CHA = "CHA"
}

export enum DICE_TYPES {
  DICE_TYPE_D4 = "D4",
  DICE_TYPE_D6 = "D6",
  DICE_TYPE_D8 = "D8",
  DICE_TYPE_D10 = "D10",
  DICE_TYPE_D12 = "D12",
  DICE_TYPE_D20 = "D20"
}

export enum DICE {
  D4 = "D4",
  D6 = "D6",
  D8 = "D8",
  D10 = "D10",
  D12 = "D12",
  D20 = "D20"
}

export enum RARITY_TYPES {
  CUSTOM = "CUSTOM",
  COMMON = "COMMON",
  RARE = "RARE",
  EPIC = "EPIC",
  LEGENDARY = "LEGENDARY"
}

export enum DAMAGE_TYPES {
  SLASHING = "SLASHING",
  PIERCING = "PIERCING",
  BLUDGEONING = "BLUDGEONING",
  FIRE = "FIRE",
  COLD = "COLD",
  LIGHTNING = "LIGHTNING",
  THUNDER = "THUNDER",
  FORCE = "FORCE",
  RADIANT = "RADIANT",
  NECROTIC = "NECROTIC",
  POISON = "POISON",
  ACID = "ACID",
  PSYCHIC = "PSYCHIC"
}

export enum DAMAGE_TYPE {
  PIERCING = "PIERCING",
  BLUDGEONING = "BLUDGEONING",
  SLASHING = "SLASHING",
  COLD = "COLD",
  FIRE = "FIRE",
  LIGHTNING = "LIGHTNING",
  THUNDER = "THUNDER",
  POISON = "POISON",
  ACID = "ACID",
  NECROTIC = "NECROTIC",
  RADIANT = "RADIANT",
  FORCE = "FORCE",
  PSYCHIC = "PSYCHIC"
}

export enum COLOR_TYPES {
  WHITE = "#ffffff",
  BLUE = "#0070DD",
  PURPLE = "#A335EE",
  ORANGE = "#FFAA00",
  LIGHTER_GREY = "#5a5f6b",
  DARK_BROWN_TINT = "#2b1e18"
}

export enum ARMOR_TYPES {
  LIGHT_ARMOR = "LIGHT_ARMOR",
  MEDIUM_ARMOR = "MEDIUM_ARMOR",
  HEAVY_ARMOR = "HEAVY_ARMOR",
  SHIELD = "SHIELD"
}

export enum WEAPON_TYPES {
  SIMPLE_MELEE = "SIMPLE_MELEE",
  MARTIAL_MELEE = "MARTIAL_MELEE",
  SIMPLE_RANGED = "SIMPLE_RANGED",
  MARTIAL_RANGED = "MARTIAL_RANGED",
  FINESSE = "FINESSE",
  VERSATILE = "VERSATILE",
  TWO_HANDED = "TWO_HANDED"
}

export enum WEAPON_TRAINING {
  SIMPLE = "SIMPLE",
  MARTIAL = "MARTIAL"
}

export enum WEAPON_COMBAT_TYPE {
  MELEE = "MELEE",
  RANGED = "RANGED"
}

export enum WEAPON_PROPERTY {
  AMMUNITION = "AMMUNITION",
  FINESSE = "FINESSE",
  HEAVY = "HEAVY",
  LIGHT = "LIGHT",
  LOADING = "LOADING",
  RANGE = "RANGE",
  REACH = "REACH",
  THROWN = "THROWN",
  TWO_HANDED = "TWO_HANDED",
  VERSATILE = "VERSATILE"
}

export enum WEAPON_MASTERY {
  CLEAVE = "CLEAVE",
  GRAZE = "GRAZE",
  NICK = "NICK",
  PUSH = "PUSH",
  SAP = "SAP",
  SLOW = "SLOW",
  TOPPLE = "TOPPLE",
  VEX = "VEX"
}

export enum CURRENCY_TYPE {
  CP = "CP",
  SP = "SP",
  EP = "EP",
  GP = "GP",
  PP = "PP"
}

export enum SPELL_TYPES {
  CANTRIP = "CANTRIP",
  FULL_ACTION = "FULL_ACTION",
  BONUS_ACTION = "BONUS_ACTION"
}

export enum ITEM_TYPES {
  ADVENTURING_GEAR = "ADVENTURING_GEAR",
  TOOLKIT = "TOOLKIT"
}

export enum BACKGROUND_TYPES {
  RELIGIOUS = "RELIGIOUS",
  UNDERWORLD = "UNDERWORLD",
  PERFORMER = "PERFORMER",
  COMMONER = "COMMONER",
  CRAFT = "CRAFT",
  RECLUSIVE = "RECLUSIVE",
  NOBILITY = "NOBILITY",
  WILDERNESS = "WILDERNESS",
  SCHOLAR = "SCHOLAR",
  SEAFARING = "SEAFARING",
  MILITARY = "MILITARY",
  URBAN_SURVIVAL = "URBAN_SURVIVAL"
}

export enum SPECIES_TYPES {
  HUMANOID = "HUMANOID",
  FEY_ANCESTRY = "FEY_ANCESTRY",
  HARDY = "HARDY",
  ARCANE_AFFINITY = "ARCANE_AFFINITY",
  DRACONIC_LINEAGE = "DRACONIC_LINEAGE"
}

export enum CLASS_TYPES {
  MARTIAL = "MARTIAL",
  ARCANE = "ARCANE",
  DIVINE = "DIVINE",
  PRIMAL = "PRIMAL",
  SUPPORT = "SUPPORT",
  SKILL_EXPERT = "SKILL_EXPERT"
}

export enum ClassFeature {
  RAGE = "RAGE",
  UNARMORED_DEFENSE = "UNARMORED_DEFENSE",
  WEAPON_MASTERY = "WEAPON_MASTERY",
  BARDIC_INSPIRATION = "BARDIC_INSPIRATION",
  SPELLCASTING = "SPELLCASTING",
  EXPERTISE = "EXPERTISE",
  JACK_OF_ALL_TRADES = "JACK_OF_ALL_TRADES",
  BARD_SUBCLASS = "BARD_SUBCLASS",
  FONT_OF_INSPIRATION = "FONT_OF_INSPIRATION",
  COUNTERCHARM = "COUNTERCHARM",
  MAGICAL_SECRETS = "MAGICAL_SECRETS",
  SUPERIOR_INSPIRATION = "SUPERIOR_INSPIRATION",
  WORDS_OF_CREATION = "WORDS_OF_CREATION",
  DANGER_SENSE = "DANGER_SENSE",
  RECKLESS_ATTACK = "RECKLESS_ATTACK",
  BARBARIAN_SUBCLASS = "BARBARIAN_SUBCLASS",
  PRIMAL_KNOWLEDGE = "PRIMAL_KNOWLEDGE",
  ABILITY_SCORE_IMPROVEMENT = "ABILITY_SCORE_IMPROVEMENT",
  EXTRA_ATTACK = "EXTRA_ATTACK",
  FAST_MOVEMENT = "FAST_MOVEMENT",
  SUBCLASS_FEATURE = "SUBCLASS_FEATURE",
  FERAL_INSTINCT = "FERAL_INSTINCT",
  INSTINCTIVE_POUNCE = "INSTINCTIVE_POUNCE",
  BRUTAL_STRIKE = "BRUTAL_STRIKE",
  RELENTLESS_RAGE = "RELENTLESS_RAGE",
  IMPROVED_BRUTAL_STRIKE = "IMPROVED_BRUTAL_STRIKE",
  PERSISTENT_RAGE = "PERSISTENT_RAGE",
  INDOMITABLE_MIGHT = "INDOMITABLE_MIGHT",
  EPIC_BOON = "EPIC_BOON",
  PRIMAL_CHAMPION = "PRIMAL_CHAMPION"
}

export enum GENERAL_PROFICIENCIES {
  SIMPLE_WEAPONS = "SIMPLE_WEAPONS",
  MARTIAL_WEAPONS = "MARTIAL_WEAPONS",
  LIGHT_ARMOR = "LIGHT_ARMOR",
  MEDIUM_ARMOR = "MEDIUM_ARMOR",
  HEAVY_ARMOR = "HEAVY_ARMOR",
  SHIELDS = "SHIELDS"
}

export enum TOOL_PROFICIENCIES {
  THIEVES_TOOLKIT = "THIEVES_TOOLKIT",
  SMITHS_TOOLKIT = "SMITHS_TOOLKIT",
  DISGUIDE_KIT = "DISGUIDE_KIT",
  DISARM_KIT = "DISARM_KIT"
}

export enum RULE_TYPES {
  CORE = "CORE",
  COMBAT = "COMBAT",
  EXPLORATION = "EXPLORATION",
  SOCIAL = "SOCIAL",
  CONDITIONS = "CONDITIONS"
}

export enum MONSTER_TYPES {
  BEAST = "BEAST",
  UNDEAD = "UNDEAD",
  DRAGON = "DRAGON",
  HUMANOID = "HUMANOID",
  FIEND = "FIEND",
  BOSS = "BOSS"
}
