import { WEAPON_BASE } from "../codex/entries/enums";

export enum PROFICIENCY_SOURCE {
  MANUAL = "MANUAL",
  CLASS = "CLASS",
  SPECIES = "SPECIES",
  BACKGROUND = "BACKGROUND",
  FEAT = "FEAT",
  ITEM = "ITEM",
  SPELL = "SPELL",
  OTHER = "OTHER"
}

export enum PROF_LEVEL {
  NONE = "NONE",
  PROFICIENT = "PROFICIENT",
  EXPERT = "EXPERT"
}

export enum PROFICIENCY_OVERRIDE_POLICY {
  OVERRIDABLE = "OVERRIDABLE",
  LOCKED = "LOCKED"
}

export enum SKILL_PROFICIENCY {
  ACROBATICS = "ACROBATICS",
  ANIMAL_HANDLING = "ANIMAL_HANDLING",
  ARCANA = "ARCANA",
  ATHLETICS = "ATHLETICS",
  DECEPTION = "DECEPTION",
  HISTORY = "HISTORY",
  INSIGHT = "INSIGHT",
  INTIMIDATION = "INTIMIDATION",
  INVESTIGATION = "INVESTIGATION",
  MEDICINE = "MEDICINE",
  NATURE = "NATURE",
  PERCEPTION = "PERCEPTION",
  PERFORMANCE = "PERFORMANCE",
  PERSUASION = "PERSUASION",
  RELIGION = "RELIGION",
  SLEIGHT_OF_HAND = "SLEIGHT_OF_HAND",
  STEALTH = "STEALTH",
  SURVIVAL = "SURVIVAL"
}

export enum SAVING_THROW_PROFICIENCY {
  STR = "STR",
  DEX = "DEX",
  CON = "CON",
  INT = "INT",
  WIS = "WIS",
  CHA = "CHA"
}

export enum WEAPON_PROFICIENCY {
  SIMPLE = "SIMPLE",
  SIMPLE_MELEE = "SIMPLE_MELEE",
  MARTIAL = "MARTIAL",
  MARTIAL_MELEE_LIGHT = "MARTIAL_MELEE_LIGHT",
  MARTIAL_MELEE_NO_HEAVY_OR_TWO_HANDED = "MARTIAL_MELEE_NO_HEAVY_OR_TWO_HANDED",
  CLUB = WEAPON_BASE.CLUB,
  DAGGER = WEAPON_BASE.DAGGER,
  GREATCLUB = WEAPON_BASE.GREATCLUB,
  HANDAXE = WEAPON_BASE.HANDAXE,
  JAVELIN = WEAPON_BASE.JAVELIN,
  LIGHT_HAMMER = WEAPON_BASE.LIGHT_HAMMER,
  MACE = WEAPON_BASE.MACE,
  QUARTERSTAFF = WEAPON_BASE.QUARTERSTAFF,
  SICKLE = WEAPON_BASE.SICKLE,
  SPEAR = WEAPON_BASE.SPEAR,
  DART = WEAPON_BASE.DART,
  LIGHT_CROSSBOW = WEAPON_BASE.LIGHT_CROSSBOW,
  SHORTBOW = WEAPON_BASE.SHORTBOW,
  SLING = WEAPON_BASE.SLING,
  BATTLEAXE = WEAPON_BASE.BATTLEAXE,
  FLAIL = WEAPON_BASE.FLAIL,
  GLAIVE = WEAPON_BASE.GLAIVE,
  GREATAXE = WEAPON_BASE.GREATAXE,
  GREATSWORD = WEAPON_BASE.GREATSWORD,
  HALBERD = WEAPON_BASE.HALBERD,
  LANCE = WEAPON_BASE.LANCE,
  LONGSWORD = WEAPON_BASE.LONGSWORD,
  MAUL = WEAPON_BASE.MAUL,
  MORNINGSTAR = WEAPON_BASE.MORNINGSTAR,
  PIKE = WEAPON_BASE.PIKE,
  RAPIER = WEAPON_BASE.RAPIER,
  SCIMITAR = WEAPON_BASE.SCIMITAR,
  SHORTSWORD = WEAPON_BASE.SHORTSWORD,
  TRIDENT = WEAPON_BASE.TRIDENT,
  WARHAMMER = WEAPON_BASE.WARHAMMER,
  WAR_PICK = WEAPON_BASE.WAR_PICK,
  WHIP = WEAPON_BASE.WHIP,
  BLOWGUN = WEAPON_BASE.BLOWGUN,
  HAND_CROSSBOW = WEAPON_BASE.HAND_CROSSBOW,
  HEAVY_CROSSBOW = WEAPON_BASE.HEAVY_CROSSBOW,
  LONGBOW = WEAPON_BASE.LONGBOW,
  MUSKET = WEAPON_BASE.MUSKET,
  PISTOL = WEAPON_BASE.PISTOL
}

export enum ARMOR_PROFICIENCY {
  LIGHT = "LIGHT",
  MEDIUM = "MEDIUM",
  HEAVY = "HEAVY",
  SHIELD = "SHIELD"
}

export enum TOOL_PROFICIENCY {
  THIEVES_TOOLKIT = "THIEVES_TOOLKIT",
  SMITHS_TOOLKIT = "SMITHS_TOOLKIT",
  DISGUISE_KIT = "DISGUISE_KIT",
  DISARM_KIT = "DISARM_KIT"
}

export enum LANGUAGE_PROFICIENCY {
  COMMON = "COMMON",
  ABYSSAL = "ABYSSAL",
  CELESTIAL = "CELESTIAL",
  DEEP_SPEECH = "DEEP_SPEECH",
  DRACONIC = "DRACONIC",
  DRUIDIC = "DRUIDIC",
  DWARVISH = "DWARVISH",
  ELVISH = "ELVISH",
  GIANT = "GIANT",
  GNOMISH = "GNOMISH",
  GOBLIN = "GOBLIN",
  HALFLING = "HALFLING",
  INFERNAL = "INFERNAL",
  ORC = "ORC",
  PRIMORDIAL = "PRIMORDIAL",
  SYLVAN = "SYLVAN",
  THIEVES_CANT = "THIEVES_CANT",
  UNDERCOMMON = "UNDERCOMMON"
}

export const CUSTOM_LANGUAGE_PREFIX = "CUSTOM:" as const;
export type CustomLanguageProficiency = `${typeof CUSTOM_LANGUAGE_PREFIX}${string}`;
export type LanguageProficiency = LANGUAGE_PROFICIENCY | CustomLanguageProficiency;

export type CHARACTER_PROFICIENCY =
  | SKILL_PROFICIENCY
  | SAVING_THROW_PROFICIENCY
  | WEAPON_PROFICIENCY
  | ARMOR_PROFICIENCY
  | TOOL_PROFICIENCY
  | LanguageProficiency;

type BASE_PROFICIENCY_ENTRY<TProficiency extends CHARACTER_PROFICIENCY> = {
  source: PROFICIENCY_SOURCE;
  sourceStr?: string;
  proficiency: TProficiency;
  proficiencyLevel: PROF_LEVEL;
  overridePolicy?: PROFICIENCY_OVERRIDE_POLICY;
};

export type SkillProficiencyEntry = BASE_PROFICIENCY_ENTRY<SKILL_PROFICIENCY>;
export type SavingThrowProficiencyEntry =
  BASE_PROFICIENCY_ENTRY<SAVING_THROW_PROFICIENCY>;
export type WeaponProficiencyEntry = BASE_PROFICIENCY_ENTRY<WEAPON_PROFICIENCY>;
export type ArmorProficiencyEntry = BASE_PROFICIENCY_ENTRY<ARMOR_PROFICIENCY>;
export type ToolProficiencyEntry = BASE_PROFICIENCY_ENTRY<TOOL_PROFICIENCY>;
export type LanguageProficiencyEntry = BASE_PROFICIENCY_ENTRY<LanguageProficiency> & {
  customDescription?: string;
};

export type CharacterProficiencyCollections = {
  skillProficiencies: SkillProficiencyEntry[];
  savingThrowProficiencies: SavingThrowProficiencyEntry[];
  weaponProficiencies: WeaponProficiencyEntry[];
  armorProficiencies: ArmorProficiencyEntry[];
  toolProficiencies: ToolProficiencyEntry[];
  languageProficiencies: LanguageProficiencyEntry[];
};
