import { act, fireEvent, render, screen } from "@testing-library/react";
import { Provider } from "react-redux";
import { beforeEach, expect, it, vi } from "vitest";
import ToastHost from "../../src/components/ToastViewport/ToastHost";
import {
  dismissAllToasts,
  showToast,
  store,
  TOAST_POSITIONS,
  type ToastPosition
} from "../../src/store";

beforeEach(() => {
  vi.useFakeTimers();
  store.dispatch(dismissAllToasts());
});

function mount(position: ToastPosition = "top-middle") {
  store.dispatch(showToast({ text: "Saved", position }));
  store.dispatch(showToast({ text: "Other toast", position, dismissMs: 10000 }));
  render(
    <Provider store={store}>
      <ToastHost />
    </Provider>
  );
  const card = screen.getByText("Saved").closest("button")!;
  card.setPointerCapture = vi.fn();
  card.hasPointerCapture = vi.fn(() => true);
  card.releasePointerCapture = vi.fn();
  return card;
}

function pointer(card: HTMLElement, type: string, x: number, y: number, extra = {}) {
  // jsdom lacks PointerEvent; retain real DOM propagation with its pointer fields.
  fireEvent(
    card,
    Object.assign(new Event(type, { bubbles: true }), {
      pointerId: 1,
      pointerType: "touch",
      isPrimary: true,
      clientX: x,
      clientY: y,
      ...extra
    })
  );
}

it.each(TOAST_POSITIONS)(
  "dismisses only the dragged %s toast toward its screen edge",
  (position) => {
    const card = mount(position);
    const offset = position.startsWith("top-") ? -50 : 50;
    pointer(card, "pointerdown", 100, 100);
    pointer(card, "pointermove", 100, 100 + offset);
    expect(card.style.translate).toBe(`0 ${offset}px`);
    pointer(card, "pointerup", 100, 100 + offset);
    expect(screen.queryByText("Saved")).not.toBeInTheDocument();
    expect(screen.getByText("Other toast")).toBeVisible();
  }
);

it.each([
  ["short drag", 0, -20, "touch", "pointerup"],
  ["wrong direction", 0, 60, "touch", "pointerup"],
  ["horizontal drag", 80, -50, "touch", "pointerup"],
  ["mouse drag", 0, -60, "mouse", "pointerup"],
  ["cancelled gesture", 0, -60, "touch", "pointercancel"],
  ["lost capture", 0, -60, "touch", "lostpointercapture"]
] as const)("retains the toast after a %s", (_name, dx, dy, pointerType, end) => {
  const card = mount();
  pointer(card, "pointerdown", 100, 100, { pointerType });
  pointer(card, "pointermove", 100 + dx, 100 + dy, { pointerType });
  pointer(card, end, 100 + dx, 100 + dy, { pointerType });
  expect(screen.getByText("Saved")).toBeVisible();
  expect(card.style.translate).toBe("0 0px");
});

it("ignores secondary touches and retains click dismissal", () => {
  const card = mount();
  pointer(card, "pointerdown", 100, 100, { isPrimary: false });
  pointer(card, "pointerup", 100, 0, { isPrimary: false });
  expect(screen.getByText("Saved")).toBeVisible();
  fireEvent.click(card);
  expect(screen.queryByText("Saved")).not.toBeInTheDocument();
});

it("preserves automatic dismissal after a cancelled drag", () => {
  const card = mount();
  pointer(card, "pointerdown", 100, 100);
  pointer(card, "pointermove", 100, 60);
  pointer(card, "pointercancel", 100, 60);
  act(() => vi.advanceTimersByTime(6000));
  expect(screen.queryByText("Saved")).not.toBeInTheDocument();
  expect(screen.getByText("Other toast")).toBeVisible();
});

it("suppresses the click generated by an unsuccessful touch drag, then allows a tap", () => {
  const card = mount();
  pointer(card, "pointerdown", 100, 100);
  pointer(card, "pointermove", 100, 80);
  pointer(card, "pointerup", 100, 80);
  fireEvent.click(card, { detail: 1 });
  expect(screen.getByText("Saved")).toBeVisible();
  pointer(card, "pointerdown", 100, 100);
  pointer(card, "pointerup", 100, 100);
  fireEvent.click(card, { detail: 1 });
  expect(screen.queryByText("Saved")).not.toBeInTheDocument();
});
